# Generated by Django 5.2.3 on 2025-06-21 23:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Customer's full name", max_length=100)),
                ('email', models.EmailField(blank=True, help_text="Customer's email address", max_length=254, null=True)),
                ('phone', models.CharField(help_text="Customer's phone number", max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('address', models.TextField(blank=True, help_text="Customer's address", null=True)),
                ('type', models.CharField(choices=[('retail', 'Retail'), ('wholesale', 'Wholesale')], default='retail', help_text='Customer type (retail or wholesale)', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='active', max_length=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, help_text="Customer's current balance", max_digits=10)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0.0, help_text="Customer's credit limit", max_digits=10)),
                ('total_purchases', models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount of purchases', max_digits=12)),
                ('last_purchase', models.DateTimeField(blank=True, help_text='Date of last purchase', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the customer', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this customer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customers',
                'ordering': ['-created_at'],
            },
        ),
    ]
