# Generated by Django 5.2.3 on 2025-06-28 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercredit',
            name='transaction_type',
            field=models.CharField(choices=[('credit_added', 'Credit Added'), ('credit_used', 'Credit Used'), ('credit_refund', 'Credit Refund'), ('credit_earned', 'Credit Earned (Overpayment)'), ('debt_incurred', 'Debt Incurred (Underpayment)')], max_length=15),
        ),
    ]
