# Generated by Django 5.2.3 on 2025-06-23 02:00

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('unit', models.PositiveIntegerField(default=0)),
                ('sale_type', models.CharField(choices=[('wholesale', 'Wholesale'), ('retail', 'Retail')], default='retail', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sale_type', 'unit'],
                'indexes': [models.Index(fields=['sale_type'], name='products_pr_sale_ty_d5bbd6_idx')],
            },
        ),
    ]
