# Generated by Django 5.2.3 on 2025-06-29 11:08

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('unit', models.PositiveIntegerField(default=0)),
                ('sale_type', models.CharField(choices=[('wholesale', 'Wholesale'), ('retail', 'Retail')], default='retail', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sale_type', 'unit'],
                'indexes': [models.Index(fields=['sale_type'], name='products_pr_sale_ty_d5bbd6_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered_quantity', models.FloatField(help_text='Total litres/units delivered in this stock batch', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('price', models.DecimalField(decimal_places=2, help_text='Stock price', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('supplier', models.CharField(help_text='Stock supplier name', max_length=200)),
                ('cumulative_stock', models.FloatField(help_text='Total cumulative stock (previous remaining + new delivery)', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('remaining_stock', models.FloatField(help_text='Current stock remaining after sales (cumulative_stock - sold_stock)', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('sold_stock', models.FloatField(default=0.0, help_text='Total litres/units sold from current stock', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stock Data',
                'verbose_name_plural': 'Stock Data',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['supplier'], name='products_st_supplie_620165_idx')],
            },
        ),
    ]
