# Generated by Django 5.2.3 on 2025-06-26 00:35

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_stockdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Stock price', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))]),
        ),
    ]
